// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://boawefwkwcuduawevuph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvYXdlZndrd2N1ZHVhd2V2dXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzMwODgsImV4cCI6MjA2MzcwOTA4OH0.pS9PLGsMMn4TFbooQ9xMWLbVXQdpUWYn3s29NO2Xm3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);